// Generated by https://quicktype.io

export interface PropertieModel {
    id: string;
    collectionId: string;
    collectionName: string;
    created: string;
    updated: string;
    nome: string;
    status: string;
    desc_anuncio: string;
    desc: string;
    endereco: string;
    bairro: string;
    cidade: string;
    estado: string;
    cep: string;
    numero: number;
    valor: number;
    dormitorio: number;
    aluguel: number;
    condominio: number;
    iptu: number;
    banheiro: number;
    metragem: number;
    vagas: number;
    andar: number;
    pet: boolean;
    mobiliado: boolean;
    prox_metro: boolean;
    foto_principal: string;
    fotos: string[];
}
