// Generated by https://quicktype.io

export interface PropertieModel {
    id: string;
    collectionId: string;
    collectionName: string;
    created: string;
    updated: string;
    imovel: string;
    status_imovel: string;
    desc_imovel_simple: string;
    desc_imovel_completa: string;
    numero_andar: number;
    endereco: string;
    endereco_numero: number;
    endereco_bairro: string;
    endereco_cidade: string;
    endereco_estado: string;
    endereco_cep: string;
    valor_venda_imovel: number;
    qtd_dormitorio: number;
    valor_aluguel: number;
    valor_condominio: number;
    valor_iptu: number;
    qtd_banheiro: number;
    numero_metragem: number;
    qtd_vagas: number;
    aceita_pet: boolean;
    aceita_fgts: boolean;
    aceita_financimento: boolean;
    e_mobiliado: boolean;
    e_prox_metro: boolean;
    foto_principal: string;
    fotos: string[];
    caracteristicas: string[];
}
